### ISSUE TITLE
"this event no longer exists" in latest ESX

### ISSUE THREAD

**Issue by VIRUXE** [GiroudMathias/fivem-esx-js#4]
[  script:es_extended] [ERROR] Resource catcafe Used the getSharedObject Event, this event no longer exists! Visit https://documentation.esx-framework.org/tutorials/tutorials-esx/sharedevent for how to fix!

Before I fix this myself I just wanted to make you aware.

**Comment by OualiS** [comment]
Hello,

Did you fixed it ?

**Comment by VIRUXE** [comment]
> Hello,
> 
> Did you fixed it ?

Did you bother reading the esx documentation, like I pointed out?
